services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://postgres:VKeSpSQtYjCszzpfAtLOWToOROKFmFJW@postgres.railway.internal:5432/railway
    networks:
      - default

networks:
  default:
    external:
      name: bridge
