services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: "postgresql://postgres:VKeSpSQtYjCszzpfAtLOWToOROKFmFJW@interchange.proxy.rlwy.net:53800/railway"

    networks:
      - default

networks:
  default:
    external:
      name: bridge
