version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8080"
    environment:
      DATABASE_URL: postgresql://postgres:VKeSpSQtYjCszzpfAtLOWToOROKFmFJW@postgres.railway.internal:5432/railway
